plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.146'
}

evaluationDependsOnChildren()

version = "${mcversion}-${mod_version}-${tag_lanzador}"
group = "${group}"
base {
    archivesName = "${mod_named}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

def phosResources = rootProject.project(':Phosphophyllite').file('src/main/resources/').getAbsolutePath()
def quartzResources = rootProject.project(':Quartz').file('src/main/resources/').getAbsolutePath()

neoForge {
    version = "${neoversion}"

    accessTransformers.from project(':Phosphophyllite').file('src/main/resources/META-INF/accesstransformer.cfg')
    accessTransformers.from project(':Quartz').file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()
            systemProperty 'forge.enabledGameTestNamespaces', "${modid}"
            programArguments.addAll '--quickPlaySingleplayer', 'New World'
        }

        server {
            server()
            systemProperty 'forge.enabledGameTestNamespaces', "${modid}"
            programArgument '--nogui'
        }

        clientData {
            clientData()
            programArguments.addAll '--mod', "${modid}", '--all', '--output', file('src/generatedClient/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath(), '--existing', phosResources, '--existing', quartzResources
        }

        serverData {
            serverData()
            programArguments.addAll '--mod', "${modid}", '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath(), '--existing', phosResources, '--existing', quartzResources
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
            jvmArgument '-Xmx2G'
        }
    }

    mods {
        "${modid}" {
            sourceSet(sourceSets.main)
        }
        phosphophyllite {
            sourceSet(project(':Phosphophyllite').sourceSets.main)
        }
        quartz {
            sourceSet(project(':Quartz').sourceSets.main)
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
    srcDir 'src/generatedClient/resources'
}

repositories {
    mavenCentral()
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "SquidDev"
        url = "https://maven.squiddev.cc"
        content {
            includeGroup "cc.tweaked"
            includeModule("org.squiddev", "Cobalt")
        }
    }
    maven {
        url = uri("https://modmaven.dev/")
    }
    maven {
        name = "Saps"
        url = "https://maven.saps.dev/releases"
    }
    maven {
		url "https://maven.latvian.dev/releases"
		content {
			includeGroup "dev.latvian.mods"
			includeGroup "dev.latvian.apps"
		}
	}
    maven {
        name = "JitPack"
        url = "https://jitpack.io"
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven {
        name = "Curse Maven"
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    // Libraries
    compileOnly project(':Phosphophyllite')
    compileOnly project(':Quartz')

    // CC:Tweaked
    compileOnly "cc.tweaked:cc-tweaked-${mcversion}-core-api:${cc_version}"
    compileOnly "cc.tweaked:cc-tweaked-${mcversion}-forge-api:${cc_version}"
    runtimeOnly "cc.tweaked:cc-tweaked-${mcversion}-forge:${cc_version}"

    // Just Enough Items
    compileOnly "mezz.jei:jei-${mcversion}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${mcversion}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${mcversion}-neoforge:${jei_version}"

     // Mekanism
    compileOnly "mekanism:Mekanism:${mekanism_version}:api"

    //  LWJGL
    compileOnly "org.lwjgl:lwjgl-opencl:${lwjgl_version}"

    // KubeJS
    compileOnly "dev.latvian.mods:kubejs-neoforge:${kubejs_version}"
    runtimeOnly "dev.latvian.mods:kubejs-neoforge:${kubejs_version}"

    // Better Advancements Tooltips
    implementation "dev.latvian.mods:better-advanced-tooltips:${better_adv_tooltips_version}"

    // Patchouli
    compileOnly "maven.modrinth:patchouli:${patchouli_version}"
    runtimeOnly "maven.modrinth:patchouli:${patchouli_version}"


    // Neo Vitae
    runtimeOnly "maven.modrinth:modonomicon:${modonomicon_version}"
    runtimeOnly "maven.modrinth:geckolib:${geckolib_version}"

   // Applied Energistics 2
    runtimeOnly "maven.modrinth:ae2:${ae2_version}"
    runtimeOnly "maven.modrinth:guideme:${guideme_version}"


    // Ultimate Foods
    runtimeOnly "maven.modrinth:appleskin:${appleskin_version}"

    // Re Avaritia
    runtimeOnly "maven.modrinth:re-avaritia:${avaritia_version}"

    // Pipez
    runtimeOnly "maven.modrinth:pipez:${pipez_version}"

    // Functional Storage
    runtimeOnly "maven.modrinth:functional-storage:${functional_storage_version}"
    runtimeOnly "maven.modrinth:titanium:${titanium_version}"

    // Ender IO
    runtimeOnly "maven.modrinth:enderio:${enderio_version}"

    // Powah
    runtimeOnly "maven.modrinth:powah:${powah_version}"
    runtimeOnly "maven.modrinth:cloth-config:${cloth_config_version}"
}

test {
    enabled = false
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "${mod_name}",
                "Specification-Vendor"    : "${author}",
                "Specification-Version"   : "1",
                "Implementation-Title"    : "${mod_name}",
                "Implementation-Version"  : "${version}",
                "Implementation-Vendor"   : "${author}",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            mcversion           : mcversion,
            neoversion          : neoversion,
            loader_version      : loader_version,
            modid               : modid,
            mod_name            : mod_name,
            mod_version         : mod_version,
            author              : author,
            description         : description,
            license             : license,
            phos_version_range  : project.project(':Phosphophyllite').property('compatibility').toString(),
            quartz_version_range: project.project(':Quartz').property('compatibility').toString(),
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.getRelease().set(25)
    options.compilerArgs << "-Xmaxerrs" << "2000"
}
