org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

author=RogueLogix, NadienDev
modid=biggerreactors
mod_name=BiggerReactorsRevived
mod_named=Bigger Reactors Revived
description=Big Reactors, but even bigger
license=LGPL v2.1
tag_lanzador=NeoForge
group=modernmods.biggerreactorsrevived
mod_version=1.0.0

# Minecraft and NeoForge versions
mcversion=1.21.1
neoversion=21.1.240
loader_version=[4,)

# NeoForge Parchment
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Dependencies
jei_version=19.27.0.340
cc_version=1.120.2
lwjgl_version=3.3.3
mekanism_version=1.21.1-10.7.19.85
sodium_version=mc1.21.1-0.6.13-neoforge
iris_version=1.8.12+1.21.1-neoforge
kubejs_version=2101.7.2-build.374
ae2_version=19.2.17
guideme_version=21.1.17
better_adv_tooltips_version=2101.1.0-build.5
rhino_version=2101.2.8-build.91
patchouli_version=1.21.1-93-NEOFORGE
allthemodium_version=3.0.1
mekanism_generators_version=10.7.19.85
avaritia_version=1.21.1-1.4.1-release
neovitae_version=1.21.1-1.1.19
modonomicon_version=1.21.1-1.120.4
geckolib_version=tPkJmim6
ultimatefoods_version=8809454
appleskin_version=8X2x5cPC
