org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

author=RogueLogix, NadienDev
modid=biggerreactors
mod_name=BiggerReactors
mod_named=Bigger Reactors
description=Big Reactors, but even bigger
license=LGPL v2.1
tag_lanzador=NeoForge
group=modernmods.biggerreactorsrevived
mod_version=2.0.0

# Minecraft and NeoForge versions
mcversion=26.1.2
neoversion=26.1.2.107
loader_version=[4,)

# NeoForge Parchment


neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Dependencies
jei_version=29.37.0.98
cc_version=1.120.0
lwjgl_version=3.3.3
mekanism_version=1.21.1-10.7.19.85
sodium_version=mc26.1.2-0.9.1-neoforge
iris_version=1.11.2+26.1-neoforge
kubejs_version=26.1.2-8.0.6
ae2_version=AyF0Qu5L
guideme_version=ZkJhP9xE
better_adv_tooltips_version=2601.1.0-build.10
patchouli_version=2CsnFLom
allthemodium_version=YHejKr3B
avaritia_version=3NNXXUW4
neovitae_version=8Pj9oLHI
modonomicon_version=1gp5Vn3B
geckolib_version=xfVfPcoC
appleskin_version=i8MiVItH
pipez_version=1hVEeHBs
functional_storage_version=nSI7DQsa
titanium_version=tZF13NYy
enderio_version=SNsMXOPB
powah_version=bymXTkIP
cloth_config_version=TimoYzse
